version: "3.9"

services:
  frontend:
    image: front
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always

  backend:
    image: back
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: backend/.env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=dbprod
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d dbprod -U postgres"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
    restart: always

volumes:
  database:
